FROM golang:1.16-alpine

WORKDIR /app

COPY ./register_node/register_node-1.go ./register_node/register_node.go
COPY ./lib/lib-1.go ./lib/lib.go

RUN go mod init alessandro.it/app \
    && go mod tidy \
    && go mod download \
    && go build lib/lib.go

CMD [ "sh", "-c", "go run register_node/register_node.go" ]