networks:
  my_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1
          
services:
  register_node:
    build: 
      context: .
      dockerfile: register_node/Dockerfile
    networks:
      my_net:
        ipv4_address: 10.5.0.254
    ports:
      - "8000:4321" # This maps port 8000 of my host to port 4321 of container
    volumes:
      # The following volume is mounted in /var/lib/docker/volumes/app_list_volume/_data/nodes.txt
      - list_volume:/home/alessandro/Dropbox/Università/SDCC/sdcc-project/mnt
  node:
    build: 
      context: .
      dockerfile: node-algorithm-2/Dockerfile
      args:
        ALGO: ${ALGO}
    stdin_open: true 
    networks:
      - my_net
    ports:
      # - "8001:1234"
      - "1234" #  This will expose the port 1234 of the container to an ephemeral 
               #  unallocated port on the host machine. It is not equal to line
               #  24 because when use the following command
               #                docker-compose up --scale node=X
               #  when it tries to create X containers it maps port of each of
               #  them to the port 8001 of my host and this is ok for the first
               #  container, but for the second (third and so on) the port 
               #  8001 is busy
    volumes: 
      # The following volume is mounted in /var/lib/docker/volumes/app_log_volume/_data/ip_address_log.txt
      - log_node:/home/alessandro/Dropbox/Università/SDCC/sdcc-project/mnt
    links:
      - register_node
      
volumes:
  list_volume:
  log_node: