FROM golang:1.16-alpine

ARG ALGO
ENV ALGORITHM ${ALGO}

WORKDIR /app

COPY ./node/node-2.go ./node/node.go
COPY ./lib/lib-23.go ./lib/lib.go
COPY ./utils/utils-2.go ./utils/utils.go

RUN go mod init alessandro.it/app \
    && go mod tidy \
    && go mod download \
    && go build lib/lib.go \
    && go build -o main_node node/node.go

CMD [ "sh", "-c", "./main_node ${ALGORITHM}" ]